[project]
name = "coingecko_api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.15"
dependencies = [
    "dagster",
    "dagster-cloud",
    "dagster-dlt",
    "dagster-slack",
    "dlt[duckdb]",
    "python-dotenv",
    "requests",
    "requests-ratelimiter",
    "tenacity",
]

[project.optional-dependencies]
dev = [
    "dagster-webserver",
    "pytest",
]

[build-system]
requires = ["hatchling>=1.19.0"]
build-backend = "hatchling.build"

[tool.dagster]
module_name = "coingecko_api.definitions"
code_location_name = "coingecko_api"
